### ISSUE TITLE
Commande : GLPI 

### ISSUE THREAD

**Issue by JanBlatterCPNV** [CPNV-MON1/Zabbix#1]
Ajout d'une nouvelle machine pour le service ticketing (GLPI)

Au niveau des spécifications techniques : 
- Debian 11 stable
- CPU 2 Core, RAM 4 Go, HDD 32 Go

**Comment by NicolasGlassey** [comment]
@Sacha-Usan 

Je viens de vous livrer dans votre canal teams privés.
